In [1]:
!pip install tensorflow==2.0.0

     |████████████████████████████████| 86.3MB 1.2MB/s 
     |████████████████████████████████| 450kB 39.7MB/s 
     |████████████████████████████████| 3.8MB 44.2MB/s 
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow 1.15.0rc3
    Uninstalling tensorflow-1.15.0rc3:
      Successfully uninstalled tensorflow-1.15.0rc3


In [0]:
import numpy as np
import tensorflow as tf

In [3]:
print (tf.__version__)

2.0.0


In [0]:
#tf.enable_eager_execution()

In [5]:
tf.executing_eagerly()

True

## Defining Tensors

In [0]:
m1 = [[1.0, 2.0], 
      [3.0, 4.0]]
m2 = np.array([[1.0, 2.0],
              [3.0, 4.0]], dtype=np.float32)
m3 = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])

In [7]:
print(type(m1))
print(type(m2))
print(type(m3))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [0]:
t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3, dtype=tf.float32)

In [9]:
print(type(t1))
print(type(t2))
print(type(t3))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


## Numpy Compatibility

In [10]:
ndarray = np.ones([3, 3])

print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.multiply(ndarray, 42)
print(tensor)


print("And NumPy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor, 1))

print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor.numpy())

TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And NumPy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explicitly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


## Constants

In [11]:
hello = tf.constant("Hello World!")
print(hello)

tf.Tensor(b'Hello World!', shape=(), dtype=string)


In [12]:
a = tf.constant(1.5)
b = tf.constant(2.5)
print(a)
print(b)

tf.Tensor(1.5, shape=(), dtype=float32)
tf.Tensor(2.5, shape=(), dtype=float32)


## Operations


In [13]:
a_plus_b = tf.add(a, b)
print(a_plus_b)

tf.Tensor(4.0, shape=(), dtype=float32)


In [14]:
a_mul_b = tf.multiply(a, b)
print(a_mul_b)

tf.Tensor(3.75, shape=(), dtype=float32)


## Variables

In [15]:
weight = tf.Variable(tf.random_normal_initializer(stddev=0.1)([5, 2]))
print(weight)

<tf.Variable 'Variable:0' shape=(5, 2) dtype=float32, numpy=
array([[ 0.02235109,  0.05499002],
       [-0.23247968,  0.10988249],
       [-0.11427877,  0.15939556],
       [-0.02218198,  0.0386082 ],
       [-0.0570378 , -0.10571259]], dtype=float32)>


## Shape, Rank, Axis

In [16]:
t = tf.constant([1,2,3,4])
print(t.shape)

(4,)


In [17]:
t = tf.constant([[1,2],
                 [3,4]])
print(t.shape)

(2, 2)


In [18]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
print(t.shape)

(1, 2, 3, 4)


In [19]:
np.array(
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]
).shape

(1, 2, 3, 4)

## Matmul VS multiply

In [20]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
print(tf.matmul(matrix1, matrix2))

tf.Tensor([[12.]], shape=(1, 1), dtype=float32)


In [21]:
print(matrix1*matrix2)

tf.Tensor(
[[6. 6.]
 [6. 6.]], shape=(2, 2), dtype=float32)


## Watch out broadcasting

In [22]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
print(matrix1+matrix2)

tf.Tensor(
[[5. 5.]
 [5. 5.]], shape=(2, 2), dtype=float32)


In [23]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
print(matrix1+matrix2)

tf.Tensor([[5. 5.]], shape=(1, 2), dtype=float32)


## Reduce Mean/Sum

In [24]:
print(tf.reduce_mean([1, 2], axis=0))

tf.Tensor(1, shape=(), dtype=int32)


In [25]:
x = [[1., 2.],
     [3., 4.]]


print(tf.reduce_mean(x))

tf.Tensor(2.5, shape=(), dtype=float32)


In [26]:
print(tf.reduce_mean(x, axis=0))

tf.Tensor([2. 3.], shape=(2,), dtype=float32)


In [27]:
print(tf.reduce_mean(x, axis=1))

tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)


In [28]:
print(tf.reduce_mean(x, axis=-1))

tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)


In [29]:
print(tf.reduce_sum(x))

tf.Tensor(10.0, shape=(), dtype=float32)


In [30]:
print(tf.reduce_sum(x, axis=0))

tf.Tensor([4. 6.], shape=(2,), dtype=float32)


In [31]:
print(tf.reduce_sum(x, axis=-1))

tf.Tensor([3. 7.], shape=(2,), dtype=float32)


In [32]:
print(tf.reduce_mean(tf.reduce_sum(x, axis=-1)))

tf.Tensor(5.0, shape=(), dtype=float32)


## Argmax with axis

In [33]:
x = [[0, 1, 2],
     [2, 1, 0]]
print(tf.argmax(x, axis=0))

tf.Tensor([1 0 0], shape=(3,), dtype=int64)


In [34]:
print(tf.argmax(x, axis=1))

tf.Tensor([2 0], shape=(2,), dtype=int64)


In [35]:
print(tf.argmax(x, axis=-1))

tf.Tensor([2 0], shape=(2,), dtype=int64)


## Reshape, squeeze, expand_dims

In [36]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
print(t.shape)

(2, 2, 3)


In [37]:
print(tf.reshape(t, shape=[-1, 3]))

tf.Tensor(
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]], shape=(4, 3), dtype=int64)


In [38]:
print(tf.reshape(t, shape=[-1, 1, 3]))

tf.Tensor(
[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]], shape=(4, 1, 3), dtype=int64)


In [39]:
print(tf.squeeze([[0], [1], [2]]))

tf.Tensor([0 1 2], shape=(3,), dtype=int32)


In [40]:
print(tf.expand_dims([0, 1, 2], 1))

tf.Tensor(
[[0]
 [1]
 [2]], shape=(3, 1), dtype=int32)


## One hot

In [41]:
print(tf.one_hot([0, 1, 2, 0], depth=3))

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]], shape=(4, 3), dtype=float32)


## Type Casting

In [42]:
print(tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32))

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [43]:
print(tf.cast([True, False, 1 == 1, 0 == 1], tf.int32))

tf.Tensor([1 0 1 0], shape=(4,), dtype=int32)


## Create a Dataset

In [44]:
a = np.arange(10)
print(a)
ds_tensors = tf.data.Dataset.from_tensor_slices(a)

[0 1 2 3 4 5 6 7 8 9]


## Apply Transformations

In [0]:
ds_tensors = ds_tensors.map(tf.square).shuffle(20).batch(2)

## Iterate

In [46]:
print('Elements of ds_tensors:')
for _ in range(3):
  for x in ds_tensors:
    print(x)

Elements of ds_tensors:
tf.Tensor([36  4], shape=(2,), dtype=int64)
tf.Tensor([25  1], shape=(2,), dtype=int64)
tf.Tensor([49 81], shape=(2,), dtype=int64)
tf.Tensor([ 9 16], shape=(2,), dtype=int64)
tf.Tensor([64  0], shape=(2,), dtype=int64)
tf.Tensor([36 16], shape=(2,), dtype=int64)
tf.Tensor([81  9], shape=(2,), dtype=int64)
tf.Tensor([ 0 64], shape=(2,), dtype=int64)
tf.Tensor([25 49], shape=(2,), dtype=int64)
tf.Tensor([1 4], shape=(2,), dtype=int64)
tf.Tensor([ 0 25], shape=(2,), dtype=int64)
tf.Tensor([36 49], shape=(2,), dtype=int64)
tf.Tensor([64 16], shape=(2,), dtype=int64)
tf.Tensor([1 9], shape=(2,), dtype=int64)
tf.Tensor([81  4], shape=(2,), dtype=int64)
